# Generated by Django 5.0 on 2023-12-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0002_resources_crystal_resources_deuterium'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='energy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
