# Generated by Django 5.0 on 2023-12-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0003_resources_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.IntegerField(blank=True, default=0, null=True)),
                ('crystal', models.IntegerField(blank=True, default=0, null=True)),
                ('deuterium', models.IntegerField(blank=True, default=0, null=True)),
                ('energy', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(max_length=0)),
            ],
            options={
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='BuildingsResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('metal', models.IntegerField(blank=True, default=0, null=True)),
                ('crystal', models.IntegerField(blank=True, default=0, null=True)),
                ('deuterium', models.IntegerField(blank=True, default=0, null=True)),
                ('energy', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(max_length=0)),
            ],
            options={
                'db_table': 'buildings_resources',
            },
        ),
    ]
