# Generated by Django 5.0 on 2023-12-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0004_buildings_buildingsresources'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingsresources',
            name='resource_to_add',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
