# Generated by Django 5.0 on 2024-01-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0006_buildings_booster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boosters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.IntegerField(blank=True, default=0, null=True)),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'boosters',
            },
        ),
    ]
