# Generated by Django 5.0 on 2024-01-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0007_boosters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('metal', models.IntegerField(blank=True, default=0, null=True)),
                ('crystal', models.IntegerField(blank=True, default=0, null=True)),
                ('deuterium', models.IntegerField(blank=True, default=0, null=True)),
                ('metal_level', models.IntegerField(blank=True, default=0, null=True)),
                ('crystal_level', models.IntegerField(blank=True, default=0, null=True)),
                ('deuterium_level', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'planets',
            },
        ),
    ]
