# Generated by Django 5.0 on 2024-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0008_planets'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetsMultiverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('metal', models.IntegerField(blank=True, default=0, null=True)),
                ('crystal', models.IntegerField(blank=True, default=0, null=True)),
                ('deuterium', models.IntegerField(blank=True, default=0, null=True)),
                ('metal_level', models.IntegerField(blank=True, default=0, null=True)),
                ('crystal_level', models.IntegerField(blank=True, default=0, null=True)),
                ('deuterium_level', models.IntegerField(blank=True, default=0, null=True)),
                ('has_headquarter', models.BooleanField(blank=True, default=0, null=True)),
                ('life_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('fire_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('shield_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('is_discovered', models.BooleanField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'planets_multiverse',
            },
        ),
    ]
