# Generated by Django 5.0 on 2024-01-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0009_planetsmultiverse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='fire_percent',
            new_name='fire_level',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='life_percent',
            new_name='life_level',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='shield_percent',
            new_name='shield_level',
        ),
    ]
