# Generated by Django 5.0 on 2024-01-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0010_rename_fire_percent_planetsmultiverse_fire_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='fire_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='life_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='buildings',
            name='shield_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
