# Generated by Django 5.0 on 2024-01-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0012_resources_satellites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(blank=True, default=0, null=True)),
                ('life_points_starship', models.IntegerField(blank=True, default=0, null=True)),
                ('life_points_enemy', models.IntegerField(blank=True, default=0, null=True)),
                ('fire_starship', models.IntegerField(blank=True, default=0, null=True)),
                ('fire_enemy', models.IntegerField(blank=True, default=0, null=True)),
                ('shield_starship', models.IntegerField(blank=True, default=0, null=True)),
                ('shield_enemy', models.IntegerField(blank=True, default=0, null=True)),
                ('winner', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fight',
            },
        ),
    ]
