# Generated by Django 5.0 on 2024-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0014_buildings_user_id_planets_created_at_planets_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_built', models.BooleanField(blank=True, default=0, null=True)),
                ('life_level', models.IntegerField(blank=True, default=0, null=True)),
                ('fire_level', models.IntegerField(blank=True, default=0, null=True)),
                ('shield_level', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(max_length=0)),
            ],
            options={
                'db_table': 'starship',
            },
        ),
        migrations.DeleteModel(
            name='Fight',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='fire_level',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='life_level',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='shield_level',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='energy',
        ),
    ]
