# Generated by Django 5.0 on 2024-01-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0015_starship_delete_fight_remove_buildings_fire_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planetsmultiverse',
            name='has_headquarter',
        ),
        migrations.AlterField(
            model_name='planets',
            name='crystal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='deuterium',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='metal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planetsmultiverse',
            name='crystal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planetsmultiverse',
            name='deuterium',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planetsmultiverse',
            name='metal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='crystal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='deuterium',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='metal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
