# Generated by Django 5.0 on 2024-01-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0016_remove_planetsmultiverse_has_headquarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='booster',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='starship',
            name='fight_exp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
