# Generated by Django 5.0 on 2024-01-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0017_resources_booster_starship_fight_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='building_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
