# Generated by Django 5.0 on 2024-01-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0018_buildings_building_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='booster',
        ),
    ]
