# Generated by Django 5.0 on 2024-01-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0019_remove_buildings_booster'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='building_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
