# Generated by Django 5.0 on 2024-01-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0020_buildings_building_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='crystal',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='deuterium',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='metal',
        ),
    ]
