# Generated by Django 5.0 on 2024-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0021_remove_buildings_crystal_remove_buildings_deuterium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetsmultiverse',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, max_length=0, null=True),
        ),
    ]
