# Generated by Django 5.0 on 2024-01-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0022_planetsmultiverse_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('search_level', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(max_length=0)),
            ],
            options={
                'db_table': 'searches',
            },
        ),
        migrations.RemoveField(
            model_name='starship',
            name='fire_level',
        ),
        migrations.RemoveField(
            model_name='starship',
            name='life_level',
        ),
        migrations.RemoveField(
            model_name='starship',
            name='shield_level',
        ),
    ]
