# Generated by Django 5.0 on 2024-01-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0023_searches_remove_starship_fire_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='crystal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='deuterium',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='metal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
