# Generated by Django 5.0 on 2024-01-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0026_users_attempts_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pseudo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
