# Generated by Django 5.0 on 2024-01-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0027_alter_users_pseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='booster',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='crystal',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='deuterium',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='satellites',
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
