# Generated by Django 5.0.1 on 2024-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0029_remove_buildings_user_id_remove_planets_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
