# Generated by Django 5.0.1 on 2024-01-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0030_alter_users_last_login_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pseudo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('target', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=None, max_length=0, null=True)),
                ('users', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ogame.users')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
