# Generated by Django 5.0.1 on 2024-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0032_planets_updated_at_resources_harvested_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingsresources',
            old_name='deuterium',
            new_name='tritium',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='deuterium',
            new_name='tritium',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='deuterium_level',
            new_name='tritium_level',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='deuterium',
            new_name='tritium',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='deuterium_level',
            new_name='tritium_level',
        ),
        migrations.RemoveField(
            model_name='searches',
            name='deuterium',
        ),
        migrations.AddField(
            model_name='searches',
            name='tritium',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='boosters',
            name='cost',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_value',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='searches',
            name='crystal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='searches',
            name='metal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
