# Generated by Django 5.0.1 on 2024-02-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0034_alter_boosters_cost_alter_planets_crystal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='unity_link',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
    ]
