# Generated by Django 5.0.1 on 2024-06-30 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0035_users_unity_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='unity_link',
        ),
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_type', models.CharField(max_length=50)),
                ('item_used', models.IntegerField(default=0)),
                ('item_bought', models.IntegerField(default=0)),
                ('purchasable', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=None, max_length=0, null=True)),
                ('users', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ogame.users')),
            ],
            options={
                'db_table': 'shop_items',
            },
        ),
    ]
