# Generated by Django 5.0.1 on 2024-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0036_remove_users_unity_link_shopitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='item_won',
            field=models.IntegerField(default=0),
        ),
    ]
