# Generated by Django 5.0.1 on 2024-07-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0037_shopitems_item_won'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingsresources',
            old_name='metal',
            new_name='carbon',
        ),
        migrations.RenameField(
            model_name='buildingsresources',
            old_name='crystal',
            new_name='diamond',
        ),
        migrations.RenameField(
            model_name='buildingsresources',
            old_name='tritium',
            new_name='magic',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='metal',
            new_name='carbon',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='metal_level',
            new_name='carbon_level',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='crystal',
            new_name='diamond',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='crystal_level',
            new_name='diamond_level',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='metal',
            new_name='carbon',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='metal_level',
            new_name='carbon_level',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='crystal',
            new_name='diamond',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='crystal_level',
            new_name='diamond_level',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='tritium',
            new_name='magic',
        ),
        migrations.RenameField(
            model_name='planetsmultiverse',
            old_name='tritium_level',
            new_name='magic_level',
        ),
        migrations.RenameField(
            model_name='searches',
            old_name='metal',
            new_name='carbon',
        ),
        migrations.RenameField(
            model_name='searches',
            old_name='crystal',
            new_name='diamond',
        ),
        migrations.RenameField(
            model_name='searches',
            old_name='tritium',
            new_name='magic',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='tritium',
            new_name='magic',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='tritium_level',
            new_name='magic_level',
        ),
       
    ]
