# Generated by Django 5.0.1 on 2024-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0038_rename_metal_buildingsresources_carbon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='unity_link_invested',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
