# Generated by Django 5.0.1 on 2024-07-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0040_users_resources_invested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='resources_invested',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
