# Generated by Django 5.0.1 on 2024-07-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0042_users_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_resource_type', models.CharField(max_length=50)),
                ('success_value', models.IntegerField(default=0)),
                ('is_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=None, max_length=0, null=True)),
                ('users', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ogame.users')),
            ],
            options={
                'db_table': 'success',
            },
        ),
    ]
